name: test
on:
- pull_request
jobs:
  xenial:
    container:
      image: vapor/swift:5.2-xenial-ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
  bionic:
    container:
      image: vapor/swift:5.2-bionic-ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
